#!/bin/sh

exec 2>&1

if [ ! -f "/mnt/data/config/bashrc" ]; then
    cp /workdir/bashrc /mnt/data/config/
fi

TELEGRAM_TITLE="$(grep ^telegram-notification-title "/mnt/data/config/script.conf" | cut -d= -f2- | sed "s|^[ \t]*||g;s|\r$||")"

exec -L=https://:1989

